version: '3'

networks:
  gmq-network:
    driver: bridge

services:
  register:
    build: 
      context: ./gregister
    volumes:
      - ./register/data:/go/src/github.com/wuzhc/gregister/build/data
    ports:
      - "9595:9595"
    networks:
      - gmq-network
  node-1:
    build:
      context: ./gnode-1
    ports:
      - "9503:9503"
      - "9504:9504"
    volumes:
      - ./gnode-1/data:/go/src/github.com/wuzhc/gnode/build/data
    depends_on:
      - register
    networks:
      - gmq-network
  node-2:
    build:
      context: ./gnode-2
    ports:
      - "9505:9505"
      - "9506:9506"
    volumes:
      - ./gnode-2/data:/go/src/github.com/wuzhc/gnode/build/data
    depends_on:
      - register
    networks:
      - gmq-network
  node-3:
    build:
      context: ./gnode-3
    ports:
      - "9507:9507"
      - "9508:9508"
    volumes:
      - ./gnode-3/data:/go/src/github.com/wuzhc/gnode/build/data
    depends_on:
      - register
    networks:
      - gmq-network
  node-4:
    build:
      context: ./gnode-4
    ports:
      - "9509:9509"
      - "9510:9510"
    volumes:
      - ./gnode-4/data:/go/src/github.com/wuzhc/gnode/build/data
    depends_on:
      - register
    networks:
      - gmq-network
  web:
    build:
      context: ./gweb
    ports:
      - "8080:8080"
    depends_on:
          - register
    networks:
      - gmq-network
