FROM wuzhc/gmq-image:v1
MAINTAINER "wuzhc2016@163.com"
CMD ["-node_id=3", "-tcp_addr=node-3:9507", "-http_addr=node-3:9508", "-register_addr=http://register:9595"]
ENTRYPOINT ["/gnode"]
EXPOSE 9507 9508
