FROM wuzhc/gmq-image:v1
MAINTAINER "wuzhc2016@163.com"
CMD ["-node_id=2", "-tcp_addr=node-2:9505", "-http_addr=node-2:9506", "-register_addr=http://register:9595"]
ENTRYPOINT ["/gnode"]
EXPOSE 9505 9506
